<?xml version="1.0" encoding="utf-8"?><Database Name="Gestion_Notes_BDD" Class="DataContextGestionNotesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=Gestion_Notes_BDD;Integrated Security=True" SettingsObjectName="ExamORM.Properties.Settings" SettingsPropertyName="Gestion_Notes_BDDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.classe" Member="classe">
    <Type Name="classe">
      <Column Name="id_classe" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="libelle_court" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="classe_suivre" Member="suivre" ThisKey="id_classe" OtherKey="id_classe" Type="suivre" />
      <Association Name="classe_devoir" Member="devoir" ThisKey="id_classe" OtherKey="id_classe" Type="devoir" />
      <Association Name="classe_eleve" Member="eleve" ThisKey="id_classe" OtherKey="id_classe" Type="eleve" />
    </Type>
  </Table>
  <Table Name="dbo.suivre" Member="suivre">
    <Type Name="suivre">
      <Column Name="id_classe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_matiere" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="classe_suivre" Member="classe" ThisKey="id_classe" OtherKey="id_classe" Type="classe" IsForeignKey="true" />
      <Association Name="matiere_suivre" Member="matiere" ThisKey="id_matiere" OtherKey="id_matiere" Type="matiere" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.devoir" Member="devoir">
    <Type Name="devoir">
      <Column Name="id_devoir" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date_devoir" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="coeff" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="id_matiere" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_classe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="devoir_noter" Member="noter" ThisKey="id_devoir" OtherKey="id_devoir" Type="noter" />
      <Association Name="classe_devoir" Member="classe" ThisKey="id_classe" OtherKey="id_classe" Type="classe" IsForeignKey="true" />
      <Association Name="matiere_devoir" Member="matiere" ThisKey="id_matiere" OtherKey="id_matiere" Type="matiere" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eleve" Member="eleve">
    <Type Name="eleve">
      <Column Name="id_eleve" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ddn" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mdp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_classe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="eleve_noter" Member="noter" ThisKey="id_eleve" OtherKey="id_eleve" Type="noter" />
      <Association Name="classe_eleve" Member="classe" ThisKey="id_classe" OtherKey="id_classe" Type="classe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.matiere" Member="matiere">
    <Type Name="matiere">
      <Column Name="id_matiere" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="libelle_court" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="matiere_suivre" Member="suivre" ThisKey="id_matiere" OtherKey="id_matiere" Type="suivre" />
      <Association Name="matiere_devoir" Member="devoir" ThisKey="id_matiere" OtherKey="id_matiere" Type="devoir" />
    </Type>
  </Table>
  <Table Name="dbo.noter" Member="noter">
    <Type Name="noter">
      <Column Name="id_eleve" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_devoir" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="absent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="note" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="devoir_noter" Member="devoir" ThisKey="id_devoir" OtherKey="id_devoir" Type="devoir" IsForeignKey="true" />
      <Association Name="eleve_noter" Member="eleve" ThisKey="id_eleve" OtherKey="id_eleve" Type="eleve" IsForeignKey="true" />
    </Type>
  </Table>
</Database>